-- Update RLS policies for challenges to allow service role
-- This script should be run on your database to fix challenge creation issues

-- First, check if service role policy exists
DO $$
BEGIN
    -- Drop existing policies if they exist
    DROP POLICY IF EXISTS "Service role can create auto-generated challenges" ON challenges;
    DROP POLICY IF EXISTS "Service role can update auto-generated challenges" ON challenges;
    
    -- Recreate the policies
    CREATE POLICY "Service role can create auto-generated challenges"
    ON challenges FOR INSERT
    WITH CHECK (
        auth.role() = 'service_role' AND "isAutoGenerated" = true
    );

    CREATE POLICY "Service role can update auto-generated challenges"
    ON challenges FOR UPDATE
    WITH CHECK (
        auth.role() = 'service_role' AND "isAutoGenerated" = true
    );

    -- Also ensure service role can read challenges
    CREATE POLICY IF NOT EXISTS "Service role can read challenges"
    ON challenges FOR SELECT
    USING (auth.role() = 'service_role');

    RAISE NOTICE 'Service role policies created successfully';
END $$;
