"use client"

import { useState, useEffect } from "react"
import { getTodayVideo, type VideoData } from "@/app/actions/youtube-video"
import { type Challenge } from "@/utils/challenge-constants"

// Helper function to convert VideoData to Challenge format
function videoDataToChallenge(videoData: VideoData): Challenge {
  return {
    id: videoData.id,
    title: videoData.title,
    description: videoData.description,
    thumbnailUrl: videoData.thumbnailUrl,
    videoUrl: videoData.videoUrl,
    embedUrl: videoData.embedUrl,
    duration: videoData.duration,
    difficulty: "intermediate", // Default difficulty
    createdAt: new Date().toISOString(),
    topics: Array.isArray(videoData.topics) ? videoData.topics : [],
    featured: true,
    isAutoGenerated: true,
    dailyBatch: new Date().toISOString().split('T')[0]
  }
}

export function useCurrentChallenge() {
  const [currentChallenge, setCurrentChallenge] = useState<Challenge | null>(null)
  const [challengeLoading, setChallengeLoading] = useState(true)

  useEffect(() => {
    const loadCurrentChallenge = async () => {
      try {
        setChallengeLoading(true)
        console.log("🔍 Loading today's video for homepage challenge...")
        
        // Get today's video instead of fetching challenges
        const videoData = await getTodayVideo()
        
        // Convert VideoData to Challenge format for UI compatibility
        const challenge = videoDataToChallenge(videoData)
        
        console.log("✅ Today's video loaded successfully:", challenge.id)
        setCurrentChallenge(challenge)
      } catch (error) {
        console.error("❌ Error loading today's video:", error)
        setCurrentChallenge(null)
      } finally {
        setChallengeLoading(false)
      }
    }

    loadCurrentChallenge()
  }, [])

  return {
    currentChallenge,
    challengeLoading,
    setCurrentChallenge,
  }
}
